
CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL PRIMARY KEY,
	username VARCHAR(128) NOT NULL UNIQUE,
	user_display_name VARCHAR(128) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
	room_id SERIAL PRIMARY KEY,
	channel_name VARCHAR(128) NOT NULL UNIQUE,
    -- owner_id INT NOT NULL REFERENCES users(user_id),
	is_active BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rooms_channel_name
    ON rooms (channel_name ASC);
ALTER SEQUENCE rooms_room_id_seq RESTART WITH 100000;


CREATE TABLE IF NOT EXISTS chatters (
	chatter_id SERIAL PRIMARY KEY,
	room_id INT NOT NULL REFERENCES rooms(room_id),
	user_id INT NOT NULL REFERENCES users(user_id),
	operator_id VARCHAR(128),
	last_chat_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER users_update
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER rooms_update
BEFORE UPDATE ON rooms
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER chatters_update
BEFORE UPDATE ON chatters
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at();



