root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = [
    "--listen=:4000", 
    "--headless=true", 
    "--log=false",
    "--accept-multiclient",
    "--api-version=2", 
    "exec",
    "tmp/main",
    "--",
    "-image_assetdir=static/assets",
    "-static_dir=static", 
    "-address=:8080",
    "-bot_config=secrets/dev_config.json",
  ]
  bin = "/go/bin/dlv"
  cmd = "CGO_ENABLED=0 go build -o ./tmp/main -gcflags \"all=-N -l\" server/main.go"
  delay = 10000
  exclude_dir = [
    "assets", 
    "tmp", 
    "vendor", 
    "testdata", 
    "static/assets", 
    "tools", 
    "thirdparty", 
    "static/spine", 
    "static/rooms", 
    "static/admin", 
    "web_app", 
    "static/web_app", 
    "static/public/test_csrf",
    "server/tools",
  ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "10s"
  log = "build-errors.log"
  poll = true
  poll_interval = 5000
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
