FROM golang:1.22.3

# Copy over the source and program
WORKDIR /work
RUN mkdir /ak_chibi_assets
COPY go.mod go.sum ./
COPY server/ ./server
COPY ./static /ak_chibi_assets
RUN rm -rf /ak_chibi_assets/spine/src

# BUILD
RUN go mod download && go mod verify
RUN go build -o ak_chibi_bot server/main.go
EXPOSE 8080 

# RUN
ENV GOPATH=/work
ENTRYPOINT ["/work/ak_chibi_bot", "-address=:8080", "-bot_config=/work/server/config.json"]

