FROM postgres:16.4

ADD ./secrets/postgresdb.crt /var/lib/postgresql/fullchain.pem
ADD ./secrets/postgresdb.key /var/lib/postgresql/privkey.pem
RUN chown postgres:postgres /var/lib/postgresql/fullchain.pem
RUN chown postgres:postgres /var/lib/postgresql/privkey.pem
RUN chmod 600 /var/lib/postgresql/fullchain.pem
RUN chmod 600 /var/lib/postgresql/privkey.pem

COPY ./configs/pg_hba.conf /opt/postgres/pg_hba.conf
COPY ./configs/postgresql.conf /opt/postgres/postgresql.conf
COPY ./configs/50-hba.sh /docker-entrypoint-initdb.d/50-hba.sh
RUN chown postgres:postgres /opt/postgres/pg_hba.conf
RUN chown postgres:postgres /opt/postgres/postgresql.conf
RUN chmod 600 /opt/postgres/pg_hba.conf
RUN chmod 600 /opt/postgres/postgresql.conf

CMD ["postgres", "-c", "config_file=/opt/postgres/postgresql.conf"]